<?php

include_once ('Circle1.php');
class Cylinder1 extends Circle1
{
public $height;
public function __construct($radius, $color,$height){
    parent::__construct($radius, $color);
    $this->height =$height;

}
public function calculateVolume(){
    return parent::calculateArea()*$this->height;
}
public function toString()
{
    return parent::toString().' , Height: '.$this->height; // TODO: Change the autogenerated stub
}

}